# Generated by Django 4.0.5 on 2022-06-05 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NotesTree',
            fields=[
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='note.note')),
                ('parent_id', models.BigIntegerField(default=-1)),
                ('root_id', models.BigIntegerField()),
                ('level', models.IntegerField(default=0)),
            ],
        ),
    ]
