# Generated by Django 4.0.5 on 2022-06-12 21:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_note_level_note_parent_id_note_root_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
