# Generated by Django 4.0.5 on 2022-06-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0004_alter_note_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="root_id",
        ),
    ]
